### ISSUE TITLE
"Scale" is not clear in the paper.

### ISSUE THREAD

**Issue by Limingxing00** [browatbn2/VLight#1]
Hi,

Today I had the honour to read the paper, "The Unreasonable Effectiveness of Encoder-Decoder Networks for Retinal Vessel Segmentation".

Could you explain the "Scale" in Table 1 of the paper?  What's the meaning of  " 2/2" , " [2-4] / 4" and " [2-4] / 2+3+4"? I cannot find the detail in the paper.

Best

**Comment by browatbn2** [comment]
Hi, thanks for your interest and reading the paper! 

x/y refers to the image scale for training/test. So 2/2 is two times the image size for training and test. [2-4] / 4 would mean training on a continuous range between 2x and 4x with testing on 4x image size. 2+3+4 means testing was done on scales 2, 3, and 4 and the outputs combined (averaging).

**Comment by Limingxing00** [comment]
Thank you for taking the time to answer the questions.

So when the patch size is 512x512 and the scale is 2, the input size is 256x256?

**Comment by browatbn2** [comment]
Patch size and input size are always the same. Scale 2 would double the image size, thus increase the number of patches by a factor of 4.

**Comment by Limingxing00** [comment]
Thanks!
